name: test
on:
  pull_request:
    branches: [main]
jobs:
  test:
    name: test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: xcode-select
        run : sudo xcode-select -switch /Applications/Xcode_16.app/Contents/Developer
      - name: execute
        run: xcodebuild test -skipPackagePluginValidation -testPlan SampleViewer -scheme SampleViewer -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max'
